[versions]

#Build
agp = "9.1.1"
groupID = "com.app"
subGroupID = "qaem"

#Android Configuration
compileSdk = "37"
minSdk = "24"
targetSdk = "37"
versionCode = "1"
versionName = "1.0"

#Kotlin
kotlin = "2.3.21"
kotlinxSerialization = "1.11.0"
kotlinxDatetime = "0.7.1"

#Junit
junit = "4.13.2"
junitVersion = "1.3.0"

#espresso
espressoCore = "3.7.0"

#lifeCycle & Core
lifecycleRuntimeKtx = "2.10.0"
coreKtx = "1.18.0"
appcompat = "1.7.1"

#Compose
composeBom = "2026.04.01"

#Viewmodel
lifecycle = "2.10.0"

#Navigation
navigationCompose = "2.9.8"

#Ktor
ktor = "3.4.3"

#Koin
koinBom = "4.2.1"

#Datastroe
datastorePreferences = "1.2.1"

#Coil
coilCompose = "2.7.0"

[libraries]
#Compose
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

#Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

#lifeCycle & Core
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

#Ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

#kotlinx
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }

#Koin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBom" }
koin-core = { group = "io.insert-koin", name = "koin-core" }
koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose" }

#Datastore
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }

#Coil
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }

[plugins]
#Build
android-application = { id = "com.android.application", version.ref = "agp" }

#Compose
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

#kotlinx
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }